FloorPlan resize validation
nautobot/nautobot-app-floor-plan pull request #137
Opened 2024-12-04 15:22 UTC by djhoward12

Adding validation to ensure FloorPlan can't be resized if tiles have been placed. Fixing spelling and formatting of documentation

2024-12-13 15:43 UTC, joewesch approved these changes

2024-12-13 16:02 UTC, smk4664 requested changes
We should document this change and why it is being changed, just so it is clear in the documentation if they encounter the error.

2024-12-16 13:46 UTC, djhoward12 commented
> We should document this change and why it is being changed, just so it is clear in the documentation if they encounter the error.

Updated documentation to address changes to floor plan resize validation.

2024-12-16 16:47 UTC, smk4664 approved these changes
Thanks for making the changes!

2024-12-16 16:47 UTC, merged